### PR TITLE
addressed IDD doc comments

### PR DESCRIPTION
**Pull request by shenda1**
# Description
PR is raised to address documentation comments.

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
| |

# Checklist:

- [ ] I have performed a self-review of my own code to ensure there are no formatting, vetting, linting, or security issues
- [ ] I have verified that new and existing unit tests pass locally with my changes
- [ ] I have not allowed coverage numbers to degenerate
- [ ] I have maintained at least 80% code coverage
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Backward compatibility is not broken

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration

- [ ] Documentation is hosted

### CODE REVIEW

**Review by Krunal-Thakkar — DISMISSED** [review]

**Comment by AnikaAgiwal2711** [comment]
This caution in mdm resource also needs to be in red 
image

**Comment by AnikaAgiwal2711** [comment]
Same with protection domain
image

**Comment by AnikaAgiwal2711** [comment]
Above comment applies for all instances : SDC volume mapping , SDS, Snapshot, Storage pool, Volume

**Comment by AnikaAgiwal2711** [comment]
Before "However" there should be a space 

image

**Comment by shenda1** [comment]
> Above comment applies for all instances : SDC volume mapping , SDS, Snapshot, Storage pool, Volume

@AnikaAgiwal2711 Already had discussion with @gokul-srivathsan on this. This is not what he wants as of now.

**Review by gokul-srivathsan — APPROVED** [review]
LGTM

**Review by Krunal-Thakkar — APPROVED** [review]
LGTM

**Comment by shenda1** [comment]
run e2e test

**Pull request merged**
