### PR TITLE
Multi-Cluster SDCs

### PR DESCRIPTION
**Pull request by doriac11**
# Description
- Allow the user to set multiple cluster to connect to an SDC  

# Checklist:

- [x] I have performed a self-review of my own code to ensure there are no formatting, vetting, linting, or security issues
- [x] I have verified that new and existing unit tests pass locally with my changes
- [x] I have not allowed coverage numbers to degenerate
- [x] I have maintained at least 80% code coverage
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] Backward compatibility is not broken

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration

- [x] Acceptance Tests
- [x] Manual testing on Windows, EXSi and Linux

### CODE REVIEW

**Comment by doriac11** [comment]
run e2e test

**Comment by doriac11** [comment]
run e2e test

**Comment by doriac11** [comment]
run e2e test

**Comment by doriac11** [comment]
Acceptance test failed through pipeline on something non releated to this PR:
```
[FindVolumeID] volumeID: 
--- PASS: TestAccVTreeDataSource (75.38s)
FAIL
coverage: 55.2% of statements in terraform-provider-powerflex, terraform-provider-powerflex/client, terraform-provider-powerflex/powerflex/helper, terraform-provider-powerflex/powerflex/models, terraform-provider-powerflex/powerflex/provider
FAIL	terraform-provider-powerflex/powerflex/provider	2517.147s
```

The related tests passed when I ran the acceptance tests manually

**Review by shekhar-j — APPROVED** [review]

**Review by nikitajoshi1 — APPROVED** [review]

**Review by rounak-adhikary — APPROVED** [review]

**Review by Krunal-Thakkar — APPROVED** [review]

**Comment by doriac11** [comment]
run e2e test

**Comment by shenda1** [comment]
run e2e test

**Comment by shenda1** [comment]
run e2e test

**Pull request merged**
