### PR TITLE
Github actions to check correct terraform formatting on PRs

### PR DESCRIPTION
**Pull request by rounak-adhikary**

### CODE REVIEW

**Comment by AnikaAgiwal2711** [comment]
Good idea

**Review by AnikaAgiwal2711 — APPROVED** [review]

**Comment by forrestxia** [comment]
Can one of the admins verify this patch?

**Comment by forrestxia** [comment]
run e2e test

**Review by shenda1 — APPROVED** [review]

**Comment by rounak-adhikary** [comment]
Dont have time to fix this branch. Will reopen when I have more time.

**Pull request closed without merging**
