### PR TITLE
Fixing and refactoring user resource import

### PR DESCRIPTION
**Pull request by rounak-adhikary**
Tested via
```
root@lglap049:~/terraform-provider-powerflex# go test -timeout 5h -run TestAccUserResource terraform-provider-powerflex/powerflex/provider -v -coverprofile cover.out

Mockey check failed, please add -gcflags="all=-N -l".
(Set env MOCKEY_CHECK_GCFLAGS=false to disable gcflags check) 

=== RUN   TestAccUserResource
--- PASS: TestAccUserResource (8.25s)
=== RUN   TestAccUserResourceNegative
--- PASS: TestAccUserResourceNegative (4.98s)
=== RUN   TestAccUserResourceCreateNegative
--- PASS: TestAccUserResourceCreateNegative (4.11s)
PASS
coverage: 6.8% of statements
ok      terraform-provider-powerflex/powerflex/provider 17.387s coverage: 6.8% of statements
root@lglap049:~/terraform-provider-powerflex#
```

Coverage Report
image

### CODE REVIEW

**Review by shenda1 — APPROVED** [review]

**Comment by rounak-adhikary** [comment]
run e2e test UserResource

**Comment by rounak-adhikary** [comment]
run e2e test UserResource

**Comment by rounak-adhikary** [comment]
run e2e test UserResource

**Comment by Krunal-Thakkar** [comment]
run e2e test UserResource

**Comment by rounak-adhikary** [comment]
run e2e test

**Comment by Krunal-Thakkar** [comment]
run e2e test UserResource

**Comment by rounak-adhikary** [comment]
run e2e test UserResource

**Review by Krunal-Thakkar — APPROVED** [review]

**Pull request merged**
