### PR TITLE
Map vol bug test

### PR DESCRIPTION
**Pull request by shenda1**
image

### CODE REVIEW

**Comment by rounak-adhikary** [comment]
Now that the delete issue of volume has been fixed, can we create all required volumes as part of the testcases?

**Comment by shenda1** [comment]
> Now that the delete issue of volume has been fixed, can we create all required volumes as part of the testcases? Eg in https://github.com/dell/terraform-provider-powerflex/blob/map_vol_bug_test/powerflex/sdc_volumes_mapping_resource_test.go#L17, `volume_id = "edb2a2cb00000002"` does not need to be hardcoded and the required volume can be created on-the-fly

Volumes are now created on the fly.

**Review by rounak-adhikary — DISMISSED** [review]
lgtm

**Comment by AnikaAgiwal2711** [comment]
@shenda1 : I'm trying to understand that what was the issue which was reported by Rounak after testing. Can you explain once ?

**Comment by shenda1** [comment]
> @shenda1 : I'm trying to understand that what was the issue which was reported by Rounak after testing. Can you explain once ?


The issue was in the getSdcType() which used to return the last SDC in the iteration.

**Comment by AnikaAgiwal2711** [comment]
Okay. Got it

**Review by AnikaAgiwal2711 — APPROVED** [review]

**Review by rounak-adhikary — APPROVED** [review]
lgtm

**Pull request merged**
